apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: weave-net
  name: weave-net
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: weave-net-metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: weave-net
